import { NavBar } from './components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Providers } from './provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="en">
      <body className='flex w-full max-h-screen'>
        <NavBar />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
